// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QuizBuilder.Api.Data;

#nullable disable

namespace QuizBuilder.Api.Data.Migrations
{
    [DbContext(typeof(QuizBuilderDbContext))]
    [Migration("20260713135428_AddQuizWebhookUrl")]
    partial class AddQuizWebhookUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QuizBuilder.Api.Models.AdminUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_username");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptFillBlankAnswerSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_attempt_fill_blank_answer_snapshots");

                    b.HasIndex("QuestionSnapshotId")
                        .HasDatabaseName("ix_attempt_fill_blank_answer_snapshots_question_snapshot_id");

                    b.ToTable("attempt_fill_blank_answer_snapshots", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptHotspotRegionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<Guid>("OriginalRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_region_id");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_snapshot_id");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_attempt_hotspot_region_snapshots");

                    b.HasIndex("QuestionSnapshotId")
                        .HasDatabaseName("ix_attempt_hotspot_region_snapshots_question_snapshot_id");

                    b.ToTable("attempt_hotspot_region_snapshots", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptMatchingPairSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Left")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("left");

                    b.Property<Guid>("OriginalPairId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_pair_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_snapshot_id");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("right");

                    b.HasKey("Id")
                        .HasName("pk_attempt_matching_pair_snapshots");

                    b.HasIndex("QuestionSnapshotId")
                        .HasDatabaseName("ix_attempt_matching_pair_snapshots_question_snapshot_id");

                    b.ToTable("attempt_matching_pair_snapshots", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptOptionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<Guid>("OriginalOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_option_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_snapshot_id");

                    b.HasKey("Id")
                        .HasName("pk_attempt_option_snapshots");

                    b.HasIndex("QuestionSnapshotId")
                        .HasDatabaseName("ix_attempt_option_snapshots_question_snapshot_id");

                    b.ToTable("attempt_option_snapshots", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptQuestionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid?>("ConditionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_question_id");

                    b.Property<bool?>("CorrectAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("correct_answer");

                    b.Property<Guid?>("CorrectOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correct_option_id");

                    b.Property<Guid?>("CorrectRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correct_region_id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<decimal?>("Max")
                        .HasColumnType("numeric")
                        .HasColumnName("max");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<decimal?>("Min")
                        .HasColumnType("numeric")
                        .HasColumnName("min");

                    b.Property<bool?>("Multiline")
                        .HasColumnType("boolean")
                        .HasColumnName("multiline");

                    b.Property<bool?>("Multiple")
                        .HasColumnType("boolean")
                        .HasColumnName("multiple");

                    b.Property<Guid>("OriginalQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_question_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<int?>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.Property<string>("Template")
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.Property<int?>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_attempt_question_snapshots");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_attempt_question_snapshots_attempt_id");

                    b.ToTable("attempt_question_snapshots", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.FillBlankAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_fill_blank_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_fill_blank_answers_question_id");

                    b.ToTable("fill_blank_answers", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.HotspotRegion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Height")
                        .HasColumnType("numeric")
                        .HasColumnName("height");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<decimal>("Width")
                        .HasColumnType("numeric")
                        .HasColumnName("width");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_hotspot_regions");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_hotspot_regions_question_id");

                    b.ToTable("hotspot_regions", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MatchingPair", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Left")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("left");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Right")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("right");

                    b.HasKey("Id")
                        .HasName("pk_matching_pairs");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_matching_pairs_question_id");

                    b.ToTable("matching_pairs", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConditionQuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("condition_question_id");

                    b.Property<Guid?>("PageId")
                        .HasColumnType("uuid")
                        .HasColumnName("page_id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<string>("Prompt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prompt");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<bool>("Required")
                        .HasColumnType("boolean")
                        .HasColumnName("required");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_questions_quiz_id");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator<string>("Type").HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.Property<bool?>("IsCorrect")
                        .HasColumnType("boolean")
                        .HasColumnName("is_correct");

                    b.Property<int>("Kind")
                        .HasColumnType("integer")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.HasKey("Id")
                        .HasName("pk_question_options");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_question_options_question_id");

                    b.ToTable("question_options", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuestionResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AttemptId")
                        .HasColumnType("uuid")
                        .HasColumnName("attempt_id");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("Text")
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id")
                        .HasName("pk_question_responses");

                    b.HasIndex("AttemptId")
                        .HasDatabaseName("ix_question_responses_attempt_id");

                    b.ToTable("question_responses", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccessPassword")
                        .HasColumnType("text")
                        .HasColumnName("access_password");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsGraded")
                        .HasColumnType("boolean")
                        .HasColumnName("is_graded");

                    b.Property<int?>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<bool?>("Published")
                        .HasColumnType("boolean")
                        .HasColumnName("published");

                    b.Property<bool?>("ShuffleQuestions")
                        .HasColumnType("boolean")
                        .HasColumnName("shuffle_questions");

                    b.Property<int?>("TimeLimitMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("time_limit_minutes");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebhookUrl")
                        .HasColumnType("text")
                        .HasColumnName("webhook_url");

                    b.HasKey("Id")
                        .HasName("pk_quizzes");

                    b.ToTable("quizzes", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuizAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("RespondentClientId")
                        .HasColumnType("text")
                        .HasColumnName("respondent_client_id");

                    b.Property<string>("RespondentName")
                        .HasColumnType("text")
                        .HasColumnName("respondent_name");

                    b.Property<int?>("Score")
                        .HasColumnType("integer")
                        .HasColumnName("score");

                    b.Property<bool?>("SnapshotIsGraded")
                        .HasColumnType("boolean")
                        .HasColumnName("snapshot_is_graded");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.HasKey("Id")
                        .HasName("pk_quiz_attempts");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_attempts_quiz_id");

                    b.ToTable("quiz_attempts", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuizPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid")
                        .HasColumnName("quiz_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_quiz_pages");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_quiz_pages_quiz_id");

                    b.ToTable("quiz_pages", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseBlank", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("text")
                        .HasColumnName("answer");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.HasKey("Id")
                        .HasName("pk_response_blanks");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("ix_response_blanks_response_id");

                    b.ToTable("response_blanks", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseDistribution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<int>("Points")
                        .HasColumnType("integer")
                        .HasColumnName("points");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.HasKey("Id")
                        .HasName("pk_response_distributions");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("ix_response_distributions_response_id");

                    b.ToTable("response_distributions", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Content")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("content");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.HasKey("Id")
                        .HasName("pk_response_files");

                    b.HasIndex("ResponseId")
                        .IsUnique()
                        .HasDatabaseName("ix_response_files_response_id");

                    b.ToTable("response_files", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("KeyId")
                        .HasColumnType("uuid")
                        .HasColumnName("key_id");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.Property<Guid>("ValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("value_id");

                    b.HasKey("Id")
                        .HasName("pk_response_matches");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("ix_response_matches_response_id");

                    b.ToTable("response_matches", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseSelectedOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("option_id");

                    b.Property<Guid>("ResponseId")
                        .HasColumnType("uuid")
                        .HasColumnName("response_id");

                    b.HasKey("Id")
                        .HasName("pk_response_selected_options");

                    b.HasIndex("ResponseId")
                        .HasDatabaseName("ix_response_selected_options_response_id");

                    b.ToTable("response_selected_options", (string)null);
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ConstantSumQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<int>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("constant-sum");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.DateQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("date");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.DropdownQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<Guid?>("CorrectOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correct_option_id");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("dropdown");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.FileUploadQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("file-upload");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.FillInTheBlankQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<string>("Template")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("template");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("fill-in-the-blank");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.HotspotQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<Guid?>("CorrectRegionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correct_region_id");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image_url");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("hotspot");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ImageChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<bool>("Multiple")
                        .HasColumnType("boolean")
                        .HasColumnName("multiple");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("image-choice");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MatchingQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("matching");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MatrixQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("matrix");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MultipleChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("multiple-choice");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.NumberQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<decimal?>("Max")
                        .HasColumnType("numeric")
                        .HasColumnName("max");

                    b.Property<decimal?>("Min")
                        .HasColumnType("numeric")
                        .HasColumnName("min");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("number");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.RankingQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("ranking");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.RatingQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<int>("Max")
                        .HasColumnType("integer")
                        .HasColumnName("max");

                    b.Property<int>("Min")
                        .HasColumnType("integer")
                        .HasColumnName("min");

                    b.ToTable("questions", null, t =>
                        {
                            t.Property("Max")
                                .HasColumnName("rating_question_max");

                            t.Property("Min")
                                .HasColumnName("rating_question_min");
                        });

                    b.HasDiscriminator().HasValue("rating");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.SingleChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<Guid?>("CorrectOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("correct_option_id");

                    b.ToTable("questions", null, t =>
                        {
                            t.Property("CorrectOptionId")
                                .HasColumnName("single_choice_question_correct_option_id");
                        });

                    b.HasDiscriminator().HasValue("single-choice");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.SliderQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<int>("Max")
                        .HasColumnType("integer")
                        .HasColumnName("max");

                    b.Property<int>("Min")
                        .HasColumnType("integer")
                        .HasColumnName("min");

                    b.Property<int>("Step")
                        .HasColumnType("integer")
                        .HasColumnName("step");

                    b.ToTable("questions", null, t =>
                        {
                            t.Property("Max")
                                .HasColumnName("slider_question_max");

                            t.Property("Min")
                                .HasColumnName("slider_question_min");
                        });

                    b.HasDiscriminator().HasValue("slider");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.TextQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("integer")
                        .HasColumnName("max_length");

                    b.Property<bool>("Multiline")
                        .HasColumnType("boolean")
                        .HasColumnName("multiline");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("text");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.TrueFalseQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.Property<bool?>("CorrectAnswer")
                        .HasColumnType("boolean")
                        .HasColumnName("correct_answer");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("true-false");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.WordChoiceQuestion", b =>
                {
                    b.HasBaseType("QuizBuilder.Api.Models.Question");

                    b.ToTable("questions", (string)null);

                    b.HasDiscriminator().HasValue("word-choice");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptFillBlankAnswerSnapshot", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.AttemptQuestionSnapshot", "QuestionSnapshot")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_fill_blank_answer_snapshots_attempt_question_snapsh");

                    b.Navigation("QuestionSnapshot");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptHotspotRegionSnapshot", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.AttemptQuestionSnapshot", "QuestionSnapshot")
                        .WithMany("Regions")
                        .HasForeignKey("QuestionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_hotspot_region_snapshots_attempt_question_snapshots");

                    b.Navigation("QuestionSnapshot");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptMatchingPairSnapshot", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.AttemptQuestionSnapshot", "QuestionSnapshot")
                        .WithMany("Pairs")
                        .HasForeignKey("QuestionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_matching_pair_snapshots_attempt_question_snapshots_");

                    b.Navigation("QuestionSnapshot");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptOptionSnapshot", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.AttemptQuestionSnapshot", "QuestionSnapshot")
                        .WithMany("Options")
                        .HasForeignKey("QuestionSnapshotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_option_snapshots_attempt_question_snapshots_questio");

                    b.Navigation("QuestionSnapshot");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptQuestionSnapshot", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuizAttempt", "Attempt")
                        .WithMany("QuestionSnapshots")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_attempt_question_snapshots_quiz_attempts_attempt_id");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.FillBlankAnswer", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.FillInTheBlankQuestion", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fill_blank_answers_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.HotspotRegion", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.HotspotQuestion", "Question")
                        .WithMany("Regions")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_hotspot_regions_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MatchingPair", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.MatchingQuestion", "Question")
                        .WithMany("Pairs")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_matching_pairs_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.Question", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuestionOption", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_options_questions_question_id");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuestionResponse", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuizAttempt", "Attempt")
                        .WithMany("Responses")
                        .HasForeignKey("AttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_question_responses_quiz_attempts_attempt_id");

                    b.Navigation("Attempt");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuizAttempt", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.Quiz", "Quiz")
                        .WithMany("Attempts")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_attempts_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuizPage", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.Quiz", "Quiz")
                        .WithMany("Pages")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_quiz_pages_quizzes_quiz_id");

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseBlank", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuestionResponse", "Response")
                        .WithMany("Blanks")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_blanks_question_responses_response_id");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseDistribution", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuestionResponse", "Response")
                        .WithMany("Distributions")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_distributions_question_responses_response_id");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseFile", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuestionResponse", "Response")
                        .WithOne("File")
                        .HasForeignKey("QuizBuilder.Api.Models.ResponseFile", "ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_files_question_responses_response_id");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseMatch", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuestionResponse", "Response")
                        .WithMany("Matches")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_matches_question_responses_response_id");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.ResponseSelectedOption", b =>
                {
                    b.HasOne("QuizBuilder.Api.Models.QuestionResponse", "Response")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("ResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_response_selected_options_question_responses_response_id");

                    b.Navigation("Response");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.AttemptQuestionSnapshot", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Options");

                    b.Navigation("Pairs");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuestionResponse", b =>
                {
                    b.Navigation("Blanks");

                    b.Navigation("Distributions");

                    b.Navigation("File");

                    b.Navigation("Matches");

                    b.Navigation("SelectedOptions");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.Quiz", b =>
                {
                    b.Navigation("Attempts");

                    b.Navigation("Pages");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.QuizAttempt", b =>
                {
                    b.Navigation("QuestionSnapshots");

                    b.Navigation("Responses");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.FillInTheBlankQuestion", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.HotspotQuestion", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("QuizBuilder.Api.Models.MatchingQuestion", b =>
                {
                    b.Navigation("Pairs");
                });
#pragma warning restore 612, 618
        }
    }
}
